-- First step: create a new database
create database sport_app_auth;

-- Second step: create a new table app_role
create table app_role(
id integer not null generated by default as identity,
role_name varchar(100) not null,
description varchar(255) default '',
primary key(id)
);

-- Third Step: create a new table app_user
create table app_user(
id integer not null generated by default as identity,
username varchar(100) not null,
pass varchar(1000) not null,
fullname varchar(100) not null,
role_id integer not null references app_role(id),
primary key(id)
);

